### ISSUE TITLE
Site does not work

### ISSUE THREAD

**Issue by BrianOrdonez** [moonkorea00/tech-interview-GPT#19]
I get this when I load the site
Unexpected Application Error!
o is not a constructor
TypeError: o is not a constructor
    at PS (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:80:8851)
    at OS (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:80:14273)
    at AS (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:80:15102)
    at tu (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:38:19525)
    at nh (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:43915)
    at Zp (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:39696)
    at Xy (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:39624)
    at bi (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:39479)
    at fs (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:35862)
    at Xp (https://tech-interview-gpt.vercel.app/assets/index-7c4e34cf.js:40:34813)

**Comment by moonkorea00** [comment]
Does this error occur on initial load? Could you provide me more details on how to reproduce the error and your local settings? Thanks.

**Comment by BrianOrdonez** [comment]
Oops. I see what happened. It works on chrome but not operagx. Strange. And yes this is when i enter this link its the immediate first thing i see https://tech-interview-gpt.vercel.app

**Comment by moonkorea00** [comment]
I see. I'll have to check out how it runs on opera. Thanks for letting me know.

**Comment by moonkorea00** [comment]
@BrianOrdonez It should work on opera now. Just that some browsers don't support the web speech api.
